BookStore/BookStore/Controllers/AuthorController.cs
using BookStore.Data;
using BookStore.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BookStore.Controllers;

[Authorize(Roles = "Admin")]
public class AuthorController : Controller
{
    private readonly BookStoreDbContext _dbContext;
    public AuthorController(BookStoreDbContext dbContext)
    {
        _dbContext = dbContext;
    }

    public IActionResult Index()
    {
        var authors = _dbContext.Authors.ToList();
        return View(authors);
    }

    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public IActionResult Create([FromForm] Author author)
    {
        var newAuthor = new Author
        {
            Name = author.Name,
            Age = author.Age,
        };

        _dbContext.Authors.Add(newAuthor);
        _dbContext.SaveChanges();

        return RedirectToAction("Index");
    }

    [HttpGet]
    public IActionResult Details([FromQuery] Guid guid)
    {
        var author = _dbContext.Authors.Include(a => a.Books).FirstOrDefault(a => a.Guid == guid);

        return View(author);
    }

    [HttpGet]
    public IActionResult Edit([FromQuery] Guid guid)
    {
        var author = _dbContext.Authors.FirstOrDefault(a => a.Guid == guid);

        return View(author);
    }

    [HttpPost]
    public IActionResult Edit([FromForm] Author author)
    {
        var updatedAuthor = _dbContext.Authors.FirstOrDefault(a => a.Guid == author.Guid);
        updatedAuthor.Name = author.Name;
        updatedAuthor.Age = author.Age;
        _dbContext.Authors.Update(updatedAuthor);
        _dbContext.SaveChanges();

        return RedirectToAction("Index");
    }

    [HttpPost]
    public IActionResult Delete([FromForm] Guid guid)
    {
        var deletedAuthor = _dbContext.Authors.FirstOrDefault(a => a.Guid == guid);

        _dbContext.Authors.Remove(deletedAuthor);
        _dbContext.SaveChanges();

        return RedirectToAction("Index");
    }
}

BookStore/BookStore/Controllers/BookController.cs
using BookStore.Data;
using BookStore.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BookStore.Controllers;



public class BookController : Controller
{
    private readonly BookStoreDbContext _dbContext;
    public BookController(BookStoreDbContext dbContext)
    {
        _dbContext = dbContext;
    }
    [Authorize(Roles = "Member, Admin")]
    public IActionResult Index(string? title, string? author, int page = 1)
    {
        Console.WriteLine("value cookies =============================");
        var expirationTime = HttpContext.Request.Cookies;

        foreach (var item in expirationTime)
        {
            Console.WriteLine(item);
        }
        Console.WriteLine(expirationTime);

        var limit = 10;
        var skip = (page - 1) * limit;
        var books = _dbContext.Books.Include(b => b.Author).ToList();

        if (title != null)
        {
            books = books.Where(b => b.Title.ToLower().Contains(title.ToLower())).ToList();
        }

        if (author != null && author != "all")
        {
            books = books.Where(b => b.Author!.Name == author).ToList();
        }

        double calculation = books.Count / (double)limit;

        var pages = (int)Math.Ceiling(calculation);

        books = books.Skip(skip).Take(limit).ToList();

        var authors = _dbContext.Authors.Select(a => a.Name).ToList();
        ViewData["authors"] = authors;
        ViewData["pages"] = pages;

        return View(books);
    }

    [HttpGet]
    public IActionResult Details([FromQuery] Guid guid)
    {
        var book = _dbContext.Books.Include(b => b.Author).FirstOrDefault(b => b.Guid == guid);

        if (book is null)
        {
            ViewData["Error"] = "Book detail is not found!";
            return RedirectToAction("Index");
        }

        return View(book);
    }

    [HttpGet]
    [Authorize(Roles = "Admin")]
    public IActionResult Create()
    {
        var authors = _dbContext.Authors.ToList();
        ViewData["authors"] = authors;


        return View();
    }

    [HttpPost]
    [Authorize(Roles = "Admin")]
    public IActionResult Create([FromForm] Book book)
    {
        if (ModelState.IsValid)
        {
            try
            {
                _dbContext.Books.Add(book);
                _dbContext.SaveChanges();

                TempData["Success"] = "Successfully to created new book";


                return RedirectToAction("Index");
            }
            catch
            {
                TempData["Error"] = "Failed to created new book";
                return RedirectToAction("Index");
            }

        }

        var authors = _dbContext.Authors.ToList();
        ViewData["authors"] = authors;


        return View();

    }

    [HttpGet]
    [Authorize(Roles = "Admin")]
    public IActionResult Edit([FromQuery] Guid guid)
    {
        var book = _dbContext.Books.FirstOrDefault(b => b.Guid == guid);

        var authors = _dbContext.Authors.ToList();
        ViewData["authors"] = authors;

        return View(book);
    }

    [HttpPost]
    [Authorize(Roles = "Admin")]
    public IActionResult Edit([FromForm] Book book)
    {
        if (ModelState.IsValid)
        {
            var updatedBook = _dbContext.Books.FirstOrDefault(b => b.Guid == book.Guid);

            if (updatedBook == null)
            {
                TempData["Error"] = "Book is not found!";
                return RedirectToAction("Index");
            }
            updatedBook.Title = book.Title;
            updatedBook.Quota = book.Quota;
            updatedBook.Price = book.Price;
            updatedBook.AuthorGuid = book.AuthorGuid;

            try
            {
                _dbContext.Books.Update(updatedBook);
                _dbContext.SaveChanges();
                TempData["Success"] = "Successfully to updated book";
                return RedirectToAction("Index");
            }
            catch
            {
                TempData["Error"] = "Failed to updated book";
                return RedirectToAction("Index");
            }
        }

        var authors = _dbContext.Authors.ToList();
        ViewData["authors"] = authors;
        return View();
    }

    [HttpPost]
    [Authorize(Roles = "Admin")]
    public IActionResult Delete([FromForm] Guid guid)
    {
        var deletedBook = _dbContext.Books.FirstOrDefault(a => a.Guid == guid);
        if (deletedBook == null)
        {
            TempData["Error"] = "Book is not found";
            return RedirectToAction("Index");
        }

        try
        {
            _dbContext.Remove(deletedBook);
            _dbContext.SaveChanges();

            TempData["Success"] = "Successfully to deleted book";
            return RedirectToAction("Index");
        }
        catch
        {
            TempData["Error"] = "Failed to deleted book";
            return RedirectToAction("Index");
        }
    }

}

BookStore/BookStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookStrore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BookStrore.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BookStrore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                        }

                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Author" asp-action="Index">Author List</a>
                            </li>
                        }
                        
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Index">Book List</a>
                            </li>
                        }

                        @if (!User.Identity.IsAuthenticated)
                        {
                            

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="SignIn">SignIn</a>
                            </li>
                        }
                        

                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="SignOut">SignOut</a>
                            </li>
                        }
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>