IdentityApp/IdentityApp/Models/Domain/ApplicationUser.cs
using Microsoft.AspNetCore.Identity;

namespace IdentityApp.Models.Domain;

public class ApplicationUser : IdentityUser
{
    public string Name { get; set; }
    public string? ProfilePicture { get; set; }
}

IdentityApp/IdentityApp/Models/Domain/DatabaseContext.cs
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;

namespace IdentityApp.Models.Domain;

public class DatabaseContext : IdentityDbContext<ApplicationUser>
{
    public DatabaseContext(DbContextOptions<DatabaseContext> options) : base(options)
    {

    }
}

IdentityApp/IdentityApp/Models/Dtos/LoginDto.cs
namespace IdentityApp.Models.Dtos;

public class LoginDto
{
    public string Username { get; set; }

    public string Password { get; set; }
}

IdentityApp/IdentityApp/Models/Dtos/RegistrationDto.cs
using System.ComponentModel.DataAnnotations;

namespace IdentityApp.Models.Dtos;

public class RegistrationDto
{
    [Required]
    public string Name { get; set; }

    [EmailAddress]
    public string Email { get; set; }

    public string Username { get; set; }

    [RegularExpression(@"^(?:(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).*)$", ErrorMessage = "minimum length password 6 and must contain 1 uppercase, 1 lowercase, 1 special character ")]
    public string Password { get; set; }

    [Compare("Password")]
    public string PasswordConfirm { get; set; }

    public string? Role { get; set; }
}

IdentityApp/IdentityApp/Models/Dtos/StatusDto.cs
namespace IdentityApp.Models.Dtos;

public class StatusDto
{
    public int StatusCode { get; set; }
    public string Message { get; set; }
}

IdentityApp/IdentityApp/Models/ErrorViewModel.cs
namespace IdentityApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

IdentityApp/IdentityApp/Controllers/AdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace IdentityApp.Controllers;

[Authorize(Roles = "Admin")]
public class AdminController : Controller
{
    public IActionResult Index()
    {
        return View();
    }
}

IdentityApp/IdentityApp/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace IdentityApp.Controllers;

[Authorize]
public class DashboardController : Controller
{
    public IActionResult Index()
    {
        Console.WriteLine("User Id: " + User.FindFirstValue(ClaimTypes.NameIdentifier));
        Console.WriteLine("Username: " + User.FindFirstValue(ClaimTypes.Name));
        Console.WriteLine("Role: " + User.FindFirstValue(ClaimTypes.Role));
        Console.WriteLine("Country: " + User.FindFirstValue(ClaimTypes.Country));
        Console.WriteLine("Expired: " + User.FindFirstValue(ClaimTypes.Expired));
        Console.WriteLine("Email: " + User.FindFirstValue(ClaimTypes.Email));
        Console.WriteLine("MobilePhone: " + User.FindFirstValue(ClaimTypes.MobilePhone));
        Console.WriteLine("Expiration: " + User.FindFirstValue(ClaimTypes.Expiration));
        Console.WriteLine("DateofBith: " + User.FindFirstValue(ClaimTypes.DateOfBirth));
        Console.WriteLine("Gender: " + User.FindFirstValue(ClaimTypes.Gender));
        Console.WriteLine("Name: " + User.FindFirstValue("Name"));

        return View();
    }
}

IdentityApp/IdentityApp/Controllers/HomeController.cs
using IdentityApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace IdentityApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

IdentityApp/IdentityApp/Controllers/UserAuthenticationController.cs
using IdentityApp.Models.Dtos;
using IdentityApp.Repositories.Abstract;
using Microsoft.AspNetCore.Mvc;

namespace IdentityApp.Controllers;

public class UserAuthenticationController : Controller
{
    private readonly IUserAuthenticationService _service;

    public UserAuthenticationController(IUserAuthenticationService service)
    {
        _service = service;
    }

    public IActionResult Registration()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Registration(RegistrationDto model)
    {
        if (!ModelState.IsValid)
        {

            return View();
        }

        model.Role = "User";
        var result = await _service.RegistrationAsync(model);

        if (result.StatusCode == 1)
        {
            TempData["Success"] = result.Message;
            return RedirectToAction("Registration");
        }
        else
        {
            TempData["Error"] = result.Message;
            return RedirectToAction("Registration");
        }
    }
    public IActionResult Login()
    {
        if (HttpContext.User.Identity.IsAuthenticated)
        {
            return RedirectToAction("Index", "Dashboard");
        }
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Login(LoginDto model)
    {
        if (!ModelState.IsValid)
        {
            return View();
        }

        var result = await _service.LoginAsync(model);

        if (result.StatusCode == 1)
        {
            return RedirectToAction("Index", "Dashboard");
        }
        else
        {
            TempData["Error"] = result.Message;
            return RedirectToAction("Login");
        }

    }

    public async Task<IActionResult> Logout()
    {
        await _service.LogoutAsync();
        return RedirectToAction("Login");
    }

    public async Task<IActionResult> CreateAdmin()
    {
        var model = new RegistrationDto
        {
            Username = "febri",
            Name = "febrianto",
            Email = "optimusprime200039@gmail.com",
            Password = "!Admin123"
        };

        model.Role = "Admin";
        var result = await _service.RegistrationAsync(model);
        return Ok(result);

    }

}

IdentityApp/IdentityApp/Views/Admin/Index.cshtml
@{
    Layout = "_Layout";
    ViewData["Title"] = "admin";
    string username = User.Identity.Name;
}

<h1>Admin Page</h1>
<p>Hello @username</p>

IdentityApp/IdentityApp/Views/Dashboard/Index.cshtml
@{
    Layout = "_Layout";
    ViewData["Title"] = "Dashboard";

    string username = User.Identity.Name;
    
}

<h1>Dashboard</h1>
<p>Hello @username</p>

IdentityApp/IdentityApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

IdentityApp/IdentityApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - IdentityApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/IdentityApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">IdentityApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Dashboard" asp-action="Index">Dashboard</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="UserAuthentication" asp-action="Logout">Logout</a>
                            </li>
                        }
                        
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Admin</a>
                            </li>
                        }
                        
                        @if (!User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="UserAuthentication" asp-action="Login">Login</a>
                            </li>
                        }
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - IdentityApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

IdentityApp/IdentityApp/Views/UserAuthentication/Login.cshtml
@model IdentityApp.Models.Dtos.LoginDto;

@{
    Layout = "_Layout";
    ViewData["Title"] = "login";
    var expired = Context.Request.Cookies["expired"];
}

@if (TempData["Success"] != null)
{
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <p>@TempData["Success"]</p>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}

@if (TempData["Error"] != null)
{
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <p>@TempData["Error"]</p>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}

@if (expired == "true")
{
    <script>

        alert("Your session has expired. Please log in again.");

    </script>
}

<h1>Login Page</h1>

<div class="card" style="width: 20rem;">
  <div class="card-body">
    <h5 class="card-title mb-5">Form Login</h5>

        <form asp-action="Login" method="post">
            <div class="mb-3">
                <label class="form-label" asp-for="Username">Username</label>
                <input class="form-control" asp-for="Username">
                <span class="text-danger" asp-validation-for="Username"></span>
            </div>
            <div class="mb-3">
                <label class="form-label" asp-for="Password">Password</label>
                <input type="text" class="form-control" asp-for="Password">
                <span class="text-danger" asp-validation-for="Password"></span>
            </div>
            
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
        <a asp-action="Registration">Not a user!, sign up!</a>
  </div>
</div>



@section Scripts {
    <script>
        // Function to remove a cookie by setting its expiration to the past
        function removeCookie(name) {
            document.cookie = name + "=; expires=Thu, 01 Jan 1970 00:00:00 UTC; path=/;";
        }

        // Call the function to remove a cookie named "MyCookie"
        removeCookie("expired");
    </script>
}

IdentityApp/IdentityApp/Views/UserAuthentication/Registration.cshtml
@model IdentityApp.Models.Dtos.RegistrationDto;

@{
    Layout = "_Layout";
    ViewData["Title"] = "Registration";
}

@if(TempData["Success"] != null)
{
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <p>@TempData["Success"]</p>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}

@if (TempData["Error"] != null)
{
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <p>@TempData["Error"]</p>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}

<h1>Registration Page</h1>

<div class="card" style="width: 20rem;">
    <div class="card-body">
        <h5 class="card-title mb-5">Form Login</h5>

        <form asp-action="Registration" method="post">
            <div class="mb-3">
                <label class="form-label" asp-for="Name">Name</label>
                <input class="form-control" asp-for="Name">
                <span class="text-danger" asp-validation-for="Name"></span>
            </div>
            <div class="mb-3">
                <label class="form-label" asp-for="Username">Username</label>
                <input class="form-control" asp-for="Username">
                <span class="text-danger" asp-validation-for="Username"></span>
            </div>
            <div class="mb-3">
                <label class="form-label" asp-for="Email">Email</label>
                <input class="form-control" asp-for="Email">
                <span class="text-danger" asp-validation-for="Email"></span>
            </div>
            <div class="mb-3">
                <label class="form-label" asp-for="Password">Password</label>
                <input type="text" class="form-control" asp-for="Password">
                <span class="text-danger" asp-validation-for="Password"></span>
            </div>

            <div class="mb-3">
                <label class="form-label" asp-for="PasswordConfirm">PasswordConfirm</label>
                <input class="form-control" asp-for="PasswordConfirm">
                <span class="text-danger" asp-validation-for="PasswordConfirm"></span>
            </div>

            <button type="submit" class="btn btn-primary">Register</button>
        </form>

        <a asp-action="Login">Have account? Login</a>
    </div>
</div>